package core.strings

const val DEFAULT_IMG_URL = "DEFAULT_IMG_URL"

const val ERROR_INVALID_VERIFICATION_CODE = "ERROR_INVALID_VERIFICATION_CODE"
const val ERROR_INVALID_PHONE_NUMBER = "ERROR_INVALID_PHONE_NUMBER"

const val SMS_TIMEOUT_SECONDS = 60L